// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxlxeljdtnqtdioyofns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4bHhlbGpkdG5xdGRpb3lvZm5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NDc4ODcsImV4cCI6MjA3MDQyMzg4N30.-bld_c6b5RhOxHUqPneYn69HhfCDkPqlxkTQvDxvIUw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});